apiVersion: v1
kind: pod
metadata: 
  name: hello-pod
spec:
  containers:
  - name: first-container
    image: nginx
    ports: 
    - container: 80
    
  labels: 
    name: 
spec:
  containers:
  - name: 
    image: 
    resources:
      limits:
        memory: 
        cpu: 
    ports:
      - containerPort: 
